#! python3
# classvars.py  
# class variables vs instantiated variables

from dataclasses import dataclass

@dataclass
class actor():
    error_count = 0 
    unknown_count = 0 
    counters = {'Natural 1 Count': 0, 'Natural 20 Count': 0, 'Natural 100 Count': 0}
    def __init__(self, name, player, logs_bin=[]):
        self.name = name
        self.player = player 
        self.logs_bin = logs_bin
        logs_count = len(logs_bin)
        if logs_count > 0:
            for i in range(0,logs_count): 
                roll_count += logs_bin[i].roll_count
        else:
            roll_count = 0
        self.roll_count = roll_count
        return
    
    def add_log(self, log_entry):
        self.logs_bin.append(log_entry)
        self.logs_count = len(self.logs_bin)
        self.roll_count = self.roll_count + log_entry.roll_count

        counters_types = list(self.counters)
        for type in counters_types:
            self.counters[type] += log_entry.counters[type]
            print("Actor", type, self.counters[type])
        if log_entry.error_flag:
            self.error_count += 1
        if log_entry.unknown_flag: 
            self.unknown_count += 1
        return 
    
class log_entry():
    acceptable_types = ["Unknown", "Initiative", "Level Up", "Will Saving Throw", "Reflex Saving Throw", 
                        "Fortitude Saving Throw", 'Unknown Saving Throw', "Skill Check", "Attack",
                        "Spell Cast", "Item / Potion Used", "Raw Roll", "Chat Message", "Ability Test",
                        "Combat Maneuver Bonus", "Caster Level Check", "Defenses", "Concentration Check", "Error"]
    error_flag = False 
    unknown_flag = True 
    counters = {'Natural 1 Count': 0, 'Natural 20 Count': 0, 'Natural 100 Count': 0}
    
    def add_roll(self, roll_object):
        if len(self.roll_bin) >= 0:
            self.roll_bin.append(roll_object)
        else:
            self.roll_bin = [roll_object]
        self.roll_count = len(self.roll_bin)
        counter_types = list(self.counters.keys())
        for type in counter_types:
            self.counters[type] += roll_object.counters[type]
            print("Log", type, self.counters[type])
        return 
    
    def update_type(self, roll_type):
        if self.entry_type == "Error":
            self.error_flag = True
        if self.entry_type == "Unknown":
            self.unknown_flag = True
        if roll_type in self.acceptable_types:
            self.entry_type = roll_type
            self.unknown_flag = False
            self.error_flag = False
        elif roll_type:
            self.entry_type = "Error"
            self.error_flag = True
            print(self.date_time)
        else: 
            self.entry_type = "Unknown"
            self.unknown_flag = True
        return self.entry_type

    def __init__(self, date_time, actor, log_lines, entry_type):
        self.date_time = date_time
        self.actor = actor
        self.log_lines = log_lines 
        self.roll_bin = []
        if entry_type in self.acceptable_types:
            self.entry_type = entry_type
        elif entry_type:
            self.entry_type = "Error"
            self.error_count += 1
        else: 
            self.entry_type = "Unknown"
            self.unknown_count += 1
        return
    
class die_roll():
    counters = {'Natural 1 Count': 0, 'Natural 20 Count': 0, 'Natural 100 Count': 0}

    def __init__(self, dx_type, dx_result, result_w_mods):
        self.dx_type = dx_type
        self.dx_result = dx_result
        if result_w_mods:
            self.result_w_mods = result_w_mods
        else: 
            self.result_w_mods = dx_result

        self.counters = self.notable_rolls(dx_type, dx_result)
        return
    
    def notable_rolls(self, dx_type, dx_result):
        if dx_result == 1:
            self.counters['Natural 1 Count'] += 1
        
        if dx_result == 20 and dx_type == "d20":
            self.counters['Natural 20 Count'] += 1

        if dx_result == 100 and dx_type == "d100":
            self.counters['Natural 100 Count'] += 1
        return self.counters
    
def main():
    sample_actor = actor("Name", "Player")
    a_roll = ['----', '(2020, 12, 10)', 'NPCRoller', 'attack', 'attack 20 damage 15', 'pew pew']
    a_log = log_entry(a_roll[1], a_roll[2], a_roll, "Attack")
    a_roll = die_roll("d20", 20, 20)
    a_log.add_roll(a_roll)
    sample_actor.add_log(a_log)

    print("Roll Nat 20 Count", a_roll.counters["Natural 20 Count"])
    print("Log Nat 20 Count", a_log.counters["Natural 20 Count"])
    print("Actor Nat 20 Count", sample_actor.counters["Natural 20 Count"])

main()
