#! python3

from dataclasses import dataclass
@dataclass
class campaign():
    def __init__(self, name, player_names):
        self.name = name
        self.players_list = []

        # we're assuming that the campaign gets made first, before any players, so we'll make players as part of this
        for player_name in player_names:
            # create player object, add to player list
            new_player = player(player_name, self.name)
            self.players_list.append(new_player)
        # create that gm 
        gamemaster = player("Gamemaster", self.name)
        self.players_list.append(gamemaster)
    
    def update_player_actor(self, player_name, actors_list):
        for player_obj in self.players_list: 
            if player_obj.name == player_name:
                player_to_update = player_obj
        
        for actor_name in actors_list:
            player_to_update.add_actor_from_campaign(actor_name)

    def show_player_stats(self):
        for player in self.players_list:
            print(player.name)
            for actor in player.actors_list:
                print(actor.name)

class player():
    def __init__(self, name, campaign):
        # start the player object with the name of the player and name of its campaign
        self.name = name
        
        # how do we manage making sure a player is added to multiple campaigns? what if the desired campaign object hasn't been made yet? 
        # just say NO to multiple campaigns and make a new player object for each campaign 
        self.campaign = campaign
        
        # we'll add actors later as a function 
        self.actors_list = []

    def add_actor_from_campaign(self, actor_name):
        actor_exists = isinstance(actor_name, actor)
        if actor_exists:
            if actor_name not in self.actors_list:
                self.actors_list.append(actor_name)
        else: 
            new_actor = actor(actor_name, self.name)
            self.actors_list.append(new_actor)
        return self.actors_list    

    # need to add in a function for adding an actor to the gamemaster player later since we'll be doin that 
    
class actor(): 
    def __init__(self, name, player, logs_bin=[]):
        self.name = name
        self.player = player 
        self.logs_bin = logs_bin
        logs_count = len(logs_bin)
      
def main():
    one_campaign = campaign("Pathfinder Adventure Path", ["Player1Name", "Player2Name", "Player3Name", "Player4Name"])
    one_campaign.update_player_actor("Player1Name", ["Character1", "Character2"])
    one_campaign.update_player_actor("Player2Name",["Character3"])
    one_campaign.update_player_actor("Player3Name", ["Character4"])
    one_campaign.update_player_actor("Gamemaster",["Goblin", "Orc", "Dragon"])
    one_campaign.show_player_stats()

main()  
